# http://module-build.sourceforge.net/META-spec.html
#
name:         URI-scp
version:      1.0
version_from: scp.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
